name: base
channels:
  - defaults
dependencies:
  - anaconda-anon-usage=0.4.3=py310hd6b623d_100
  - anaconda-client=1.11.2=py310hca03da5_0
  - anaconda-cloud-auth=0.1.4=py310hca03da5_0
  - anaconda-navigator=2.5.0=py310hca03da5_0
  - anaconda-project=0.11.1=py310hca03da5_0
  - attrs=23.1.0=py310hca03da5_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - beautifulsoup4=4.12.2=py310hca03da5_0
  - boltons=23.0.0=py310hca03da5_0
  - brotlipy=0.7.0=py310h1a28f6b_1002
  - bzip2=1.0.8=h620ffc9_4
  - ca-certificates=2023.08.22=hca03da5_0
  - cctools=949.0.1=hc179dcd_25
  - cctools_osx-arm64=949.0.1=h332cad3_25
  - certifi=2023.7.22=py310hca03da5_0
  - cffi=1.15.1=py310h80987f9_3
  - chardet=4.0.0=py310hca03da5_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py310hca03da5_0
  - clyent=1.2.2=py310hca03da5_1
  - conda=23.9.0=py310hca03da5_0
  - conda-build=3.27.0=py310hca03da5_0
  - conda-content-trust=0.1.3=py310hca03da5_0
  - conda-index=0.3.0=py310hca03da5_0
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - conda-package-handling=2.2.0=py310hca03da5_0
  - conda-package-streaming=0.9.0=py310hca03da5_0
  - conda-repo-cli=1.0.75=py310hca03da5_0
  - conda-token=0.4.0=pyhd3eb1b0_0
  - conda-verify=3.4.2=py_1
  - cryptography=41.0.3=py310hd4332d6_0
  - cyrus-sasl=2.1.28=h9131b1a_1
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - freetype=2.12.1=h1192e45_0
  - future=0.18.3=py310hca03da5_0
  - gettext=0.21.0=h13f89a0_1
  - giflib=5.2.1=h80987f9_3
  - glib=2.69.1=h514c7bf_2
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py310h8c48613_0
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - icu=68.1=hc377ac9_0
  - idna=3.4=py310hca03da5_0
  - importlib-metadata=6.0.0=py310hca03da5_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jinja2=3.1.2=py310hca03da5_0
  - jpeg=9e=h80987f9_1
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.17.3=py310hca03da5_0
  - jupyter_core=5.3.0=py310hca03da5_0
  - keyring=23.13.1=py310hca03da5_0
  - krb5=1.20.1=hf3e1bf2_1
  - lcms2=2.12=hba8e193_0
  - ld64=530=hb29bf3f_25
  - ld64_osx-arm64=530=h001ce53_25
  - ldid=2.1.5=h20b2a84_3
  - lerc=3.0=hc377ac9_0
  - libarchive=3.6.2=h62fee54_2
  - libclang=14.0.6=default_h1b80db6_1
  - libclang13=14.0.6=default_h24352ff_1
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20221030=h80987f9_0
  - libffi=3.4.4=hca03da5_0
  - libiconv=1.16=h1a28f6b_2
  - liblief=0.12.3=h313beb8_0
  - libllvm14=14.0.6=h7ec7a93_3
  - libpng=1.6.39=h80987f9_0
  - libpq=12.15=h02f6b3c_1
  - libtiff=4.5.1=h313beb8_0
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxml2=2.10.4=h372ba2a_0
  - libxslt=1.1.37=habca612_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - markupsafe=2.1.1=py310h1a28f6b_0
  - more-itertools=8.12.0=pyhd3eb1b0_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py310hca03da5_0
  - mysql=5.7.24=ha71a6ea_2
  - navigator-updater=0.4.0=py310hca03da5_1
  - nbformat=5.9.2=py310hca03da5_0
  - ncurses=6.4=h313beb8_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=3.0.11=h1a28f6b_2
  - packaging=23.1=py310hca03da5_0
  - patch=2.7.6=h1a28f6b_1001
  - pathlib=1.0.1=pyhd3eb1b0_1
  - pcre=8.45=hc377ac9_0
  - pillow=10.0.1=py310h3b245a6_0
  - pip=22.3.1=py310hca03da5_0
  - pkce=1.0.3=py310hca03da5_0
  - pkginfo=1.9.6=py310hca03da5_0
  - platformdirs=3.10.0=py310hca03da5_0
  - pluggy=1.0.0=py310hca03da5_1
  - ply=3.11=py310hca03da5_0
  - psutil=5.9.0=py310h1a28f6b_0
  - py-lief=0.12.3=py310h313beb8_0
  - pycosat=0.6.6=py310h80987f9_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.12=py310h80987f9_1
  - pyjwt=2.4.0=py310hca03da5_0
  - pyopenssl=23.2.0=py310hca03da5_0
  - pyqt=5.15.7=py310hc377ac9_0
  - pyrsistent=0.18.0=py310h1a28f6b_0
  - pysocks=1.7.1=py310hca03da5_0
  - python=3.10.13=hb885b13_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-dotenv=0.21.0=py310hca03da5_0
  - python-fastjsonschema=2.16.2=py310hca03da5_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python.app=3=py310h1a28f6b_0
  - pytz=2023.3.post1=py310hca03da5_0
  - pyyaml=6.0.1=py310h80987f9_0
  - qt-main=5.15.2=h9b4df51_9
  - qt-webengine=5.15.9=h2903aaf_7
  - qtpy=2.2.0=py310hca03da5_0
  - qtwebkit=5.212=h19f419d_5
  - readline=8.2=h1a28f6b_0
  - requests=2.31.0=py310hca03da5_0
  - requests-toolbelt=1.0.0=py310hca03da5_0
  - ruamel.yaml=0.17.21=py310h1a28f6b_0
  - ruamel.yaml.clib=0.2.6=py310h1a28f6b_1
  - ruamel_yaml=0.17.21=py310h1a28f6b_0
  - semver=2.13.0=pyhd3eb1b0_0
  - setuptools=65.6.3=py310hca03da5_0
  - sip=6.6.2=py310hc377ac9_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.5=py310hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - sympy=1.11.1=py310hca03da5_0
  - tapi=1100.0.11=h8754e6a_1
  - tk=8.6.12=hb8d0fd4_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py310hca03da5_0
  - tornado=6.3.3=py310h80987f9_0
  - tqdm=4.65.0=py310h33ce5c2_0
  - traitlets=5.7.1=py310hca03da5_0
  - truststore=0.8.0=py310hca03da5_0
  - ujson=5.4.0=py310hc377ac9_0
  - urllib3=1.26.16=py310hca03da5_0
  - wheel=0.38.4=py310hca03da5_0
  - xz=5.4.2=h80987f9_0
  - yaml=0.2.5=h1a28f6b_0
  - zipp=3.11.0=py310hca03da5_0
  - zlib=1.2.13=h5a0b063_0
  - zstandard=0.19.0=py310h80987f9_0
  - zstd=1.5.5=hd90d995_0
  - pip:
      - anyio==3.7.1
      - appnope==0.1.3
      - asgiref==3.7.2
      - asttokens==2.4.1
      - backoff==2.2.1
      - comm==0.2.0
      - decorator==5.1.1
      - distlib==0.3.7
      - django==4.2.4
      - duckdb==0.9.1
      - duckdb-engine==0.9.2
      - exceptiongroup==1.1.3
      - executing==2.0.1
      - fastapi==0.104.1
      - filelock==3.12.4
      - greenlet==3.0.1
      - h11==0.14.0
      - ipython==8.17.2
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - jedi==0.19.1
      - jupysql==0.10.5
      - jupysql-plugin==0.2.5
      - jupyter-ui-poll==0.2.2
      - jupyterlab-widgets==3.0.9
      - matplotlib-inline==0.1.6
      - monotonic==1.6
      - msal==1.25.0
      - numpy==1.26.2
      - pandas==2.1.3
      - parso==0.8.3
      - pexpect==4.8.0
      - ploomber-core==0.2.14
      - posthog==3.0.2
      - powerbiclient==3.1.1
      - prettytable==3.9.0
      - prompt-toolkit==3.0.41
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py4j==0.10.9.7
      - pygments==2.17.1
      - pymysql==1.1.0
      - pyqt5-sip==12.11.0
      - pyspark==3.5.0
      - scipy==1.11.4
      - sniffio==1.3.0
      - sqlalchemy==2.0.23
      - sqlglot==18.13.0
      - sqlparse==0.4.4
      - stack-data==0.6.3
      - starlette==0.27.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - uvicorn==0.24.0.post1
      - virtualenv==20.24.5
      - wcwidth==0.2.10
      - widgetsnbextension==4.0.9
prefix: /Users/Aaron/anaconda3